#!/usr/bin/python3

import argparse
from pythonping import ping

class PingSweep:
    def ping(self):
        target_ip = input("Target IP: ")
        print(f"Performing a ping sweep on {target_ip}")
        # Code to perform a ping sweep
        response = ping(target_ip, verbose=True)
        return response
        
    def ping_sweep(self,verbose=False):
        results= {}
        start_ip = input("Starting IP: ")
        end_ip = input("End IP: ")
        timeout = input("Timeout: (default=1) ")
        for i in range(start_ip, end_ip + 1):
            target_ip = f"192.168.0.{i}"
            response = ping(start_ip, end_ip, timeout=int(timeout), verbose=verbose)
            results[target_ip] = response.success()
        return results

class PortScan:
    # TODO: implement network scanning using scapy, socket or pyshark libs
    def scan(self, target):
        # Code to perform a port scan
        print("Performing a port scan on target:", target)

class SNMPScan:
    # TODO: implement SNMP scanning using pysnmp or snmpy
    def scan(self, target):
        # Code to perform an SNMP scan
        print("Performing an SNMP scan on target:", target)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-sw", "--pingsweep", help="Perform a ping sweep", action="store_true")
    parser.add_argument("-ps", "--portscan", help="Perform a port scan", action="store_true")
    parser.add_argument("-sn", "--snmpscan", help="Perform an SNMP scan", action="store_true")
    args = parser.parse_args()

    if args.pingsweep:
        scan = PingSweep()
        scan.ping()
    elif args.portscan:
        scan = PortScan()
        scan.scan(args.target)
    elif args.snmpscan:
        scan = SNMPScan()
        scan.scan(args.target)
    else:
        print("No scanning technique specified. Use -h for help.")
