#!/usr/bin/python3

import os
import json
from getkey import getkey

with open("options.json", "r") as f:
    data = json.load(f)

options_dict = data["options_dict"]
pingsweep_options = data["pingsweep_options"]
portscan_options = data["portscan_options"]
snmpscan_options = data["snmpscan_options"]
sub_options_dict = data["sub_options_dict"]

class Menu:
    def __init__(self, options_dict):
        self.options_dict = options_dict
        self.current_layer = options_dict
        self.current_index = 0
    
    def display_options(self):
        print("Please choose an option:")
        for i, (key, value) in enumerate(self.current_layer.items()):
            symbol = "*" if i == self.current_index else " "
            print(f"[{symbol}] {value}")
       
    def get_choice(self):
        key = getkey()
        if key == "\x1b[A":
            if self.current_index > 0:
                self.current_index = (self.current_index - 1)
            else:
                self.current_index = len(self.current_layer) - 1
                self.display_options()
        elif key == "\x1b[B":
            if self.current_index < len(self.current_layer) - 1:
                self.current_index = (self.current_index + 1)
            else:
                self.current_index = 0
                self.display_options()
        elif key == "\n":
            selected_key = list(self.current_layer.keys())[self.current_index]
            selected_option = self.current_layer[selected_key]
            if selected_option in sub_options_dict:
                self.current_layer = sub_options_dict[selected_option]
                self.current_index = 0
                self.display_options()
            else:
                return selected_key


    
    def menu_driver(self, current_pointer=None):
        if current_pointer:
            self.current_layer = current_pointer
        while True:
            self.display_options()
            choice = self.get_choice()
            if choice is None:
                os.system('clear')
                continue
            print(f"You selected: {choice}")
            break

menu = Menu(options_dict)
menu.menu_driver()
