#!/usr/bin/python3

import os
from getkey import getkey

class Menu:
    def __init__(self, options_dict):
        self.options_dict = options_dict
        self.current_layer = options_dict
        self.current_index = 0
    
    def display_options(self):
        print("Please choose an option:")
        for i, (key, value) in enumerate(self.current_layer.items()):
            symbol = "*" if i == self.current_index else " "
            print(f"[{symbol}] {value}")
       
    def get_choice(self):
        key = getkey()
        if key == "UP":
            self.current_index = (self.current_index - 1 + len(self.current_layer)) % len(self.current_layer)
            self.display_options()
        elif key == "DOWN":
            self.current_index = (self.current_index + 1) % len(self.current_layer)
            self.display_options()
        elif key == "ENTER":
            selected_key = list(self.current_layer.keys())[self.current_index]
            selected_option = self.current_layer[selected_key]
            if selected_option in sub_options_dict:
                self.current_layer = sub_options_dict[selected_option]
                self.current_index = 0
            else:
                return selected_key
    
    def menu_driver(self, current_pointer=None):
        if current_pointer:
            self.current_layer = current_pointer
        while True:
            self.display_options()
            choice = self.get_choice()
            if choice is None:
                os.system('clear')
                continue
            print(f"You selected: {choice}")
            break

options_dict = {
    1: "pingsweep",
    2: "portscan",
    3: "snmpscan",
}

pingsweep_options = {
    1: "ping 1",
    2: "ping 2",
    3: "ping 3",
}

portscan_options = {
    1: "port 1",
    2: "port 2",
    3: "port 3",
}

snmpscan_options = {
    1: "snmp 1",
    2: "snmp 2",
    3: "snmp 3",
}

sub_options_dict = {
    "pingsweep": pingsweep_options,
    "portscan": portscan_options,
    "snmpscan": snmpscan_options,
}

menu = Menu(options_dict)
menu.menu_driver()
